name = "SauterSchwabQuadrature"
uuid = "535c7bfe-2023-5c1d-b712-654ef9d93a38"
version = "2.3.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "0.12, 1"
FastGaussQuadrature = "0.5"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"

[targets]
test = ["Test", "JuliaFormatter", "CompScienceMeshes"]