name = "SauterSchwabQuadrature"
uuid = "535c7bfe-2023-5c1d-b712-654ef9d93a38"
version = "2.1.1"

[deps]
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CompScienceMeshes = "0.2, 0.3"
FastGaussQuadrature = "0.3, 0.4"
StaticArrays = "0.12, 1"
julia = "1.6"
